//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DatabaseInitialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Messenger.DatabaseInitialization.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[Offices]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE Offices(
        ///    Id int identity(1,1) primary key,
        ///	[Number] int not null
        ///) 
        ///
        ///END.
        /// </summary>
        internal static string _10_CreateTeachersTable {
            get {
                return ResourceManager.GetString("10_CreateOfficesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[OfficesChangeLog]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE OfficesChangeLog(
        ///	Id int identity(1,1) primary key,
        ///	[OfficeId] int not null,
        ///	[Number] int not null,
        ///	[Operation] nvarchar(100) not null,
        ///	[User] nvarchar(100) not null default CURRENT_USER,
        ///	[ChangeDate] smalldatetime not null default GETDATE()
        ///)
        ///
        ///END.
        /// </summary>
        internal static string _11_CreateTasksTable {
            get {
                return ResourceManager.GetString("11_CreateOfficesChangeLogTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[Specializations]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE Specializations(
        ///    Id int identity(1,1) primary key,
        ///	[Name] nvarchar(50) not null,
        ///	[Description] nvarchar(300) not null
        ///) 
        ///
        ///END.
        /// </summary>
        internal static string _12_CreateSpecializationsTable {
            get {
                return ResourceManager.GetString("12_CreateSpecializationsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[SpecializationsChangeLog]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE SpecializationsChangeLog(
        ///	Id int identity(1,1) primary key,
        ///	[SpecializationId] int not null,
        ///	[Name] nvarchar(50) not null,
        ///	[Description] nvarchar(300) not null,
        ///	[Operation] nvarchar(100) not null,
        ///	[User] nvarchar(100) not null default CURRENT_USER,
        ///	[ChangeDate] smalldatetime not null default GETDATE()
        ///)
        ///
        ///END.
        /// </summary>
        internal static string _13_CreateSpecializationsChangeLogTable {
            get {
                return ResourceManager.GetString("13_CreateSpecializationsChangeLogTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[Doctors]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE Doctors(
        ///    Id int identity(1,1) primary key,
        ///	[Name] nvarchar(50) not null,
        ///	[Surname] nvarchar(50) not null,
        ///	[SpecializationId] int foreign key references Specializations(Id)
        ///) 
        ///
        ///END.
        /// </summary>
        internal static string _14_CreateDoctorsTable {
            get {
                return ResourceManager.GetString("14_CreateDoctorsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[DoctorsChangeLog]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE DoctorsChangeLog(
        ///	Id int identity(1,1) primary key,
        ///	[DoctorId] int not null,
        ///	[Name] nvarchar(50) not null,
        ///	[Surname] nvarchar(50) not null,
        ///	[SpecializationId] int not null,
        ///	[Operation] nvarchar(100) not null,
        ///	[User] nvarchar(100) not null default CURRENT_USER,
        ///	[ChangeDate] smalldatetime not null default GETDATE()
        ///)
        ///
        ///END.
        /// </summary>
        internal static string _15_CreateDoctorsChangeLogTable {
            get {
                return ResourceManager.GetString("15_CreateDoctorsChangeLogTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[Appointments]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE Appointments(
        ///    Id int identity(1,1) primary key,
        ///	[DoctorId] int foreign key references Doctors(Id) on delete cascade,
        ///	[OfficeId] int foreign key references Offices(Id) on delete cascade,
        ///	[StartDate] datetime not null,
        ///	[EndDate] datetime not null,
        ///	[PatientName] nvarchar(50) not null
        ///) 
        ///
        ///END.
        /// </summary>
        internal static string _16_CreateAppointmentsTable {
            get {
                return ResourceManager.GetString("16_CreateAppointmentsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[Messenger].[AppointmentsChangeLog]&apos;) AND type in (N&apos;U&apos;))
        ///
        ///BEGIN
        ///CREATE TABLE AppointmentsChangeLog(
        ///	Id int identity(1,1) primary key,
        ///	[AppointmentId] int not null,
        ///	[DoctorId] int not null,
        ///	[OfficeId] int not null,
        ///	[StartDate] datetime not null,
        ///	[EndDate] datetime not null,
        ///	[PatientName] nvarchar(50) not null,
        ///	[Operation] nvarchar(100) not null,
        ///	[User] nvarchar(100) not null default CURRENT_USER,
        ///	[ChangeDate] smal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17_CreateAppointmentsChangeLogTable {
            get {
                return ResourceManager.GetString("17_CreateAppointmentsChangeLogTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;AddOrUpdateOffices&apos;)
        ///DROP PROCEDURE AddOrUpdateOffices
        ///
        ///GO
        ///
        ///CREATE PROCEDURE AddOrUpdateOffices
        ///    @number int,
        ///	@id int = 0
        ///AS
        ///IF @id = 0
        ///	BEGIN
        ///		INSERT INTO Offices(Number) 
        ///		VALUES(@number)
        ///
        ///		SET @id = scope_identity()
        ///		RETURN @id
        ///	END
        ///ELSE
        ///	BEGIN
        ///		UPDATE Offices
        ///		SET
        ///		[Number] = @number
        ///		WHERE Id = @id
        ///	END
        ///	
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE [type] = &apos;TR&apos; AND [name] = &apos;Offices_INSERT&apos;)
        ///DR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_AddOrUpdateOffices {
            get {
                return ResourceManager.GetString("18_AddOrUpdateOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;AddOrUpdateSpecializations&apos;)
        ///DROP PROCEDURE AddOrUpdateSpecializations
        ///GO
        ///CREATE PROCEDURE AddOrUpdateSpecializations
        ///    @name nvarchar(50),
        ///	@description nvarchar(300),
        ///	@id int = 0
        ///AS
        ///IF @id = 0
        ///	BEGIN
        ///		INSERT INTO Specializations([Name], [Description])
        ///		VALUES(@name, @description)
        ///
        ///		SET @id = scope_identity()
        ///		RETURN @id
        ///	END
        ///ELSE
        ///	BEGIN
        ///		UPDATE Specializations
        ///		SET
        ///		[Name] = @name,
        ///		[Description] = @descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _19_AddOrUpdateSpecializations {
            get {
                return ResourceManager.GetString("19_AddOrUpdateSpecializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;AddOrUpdateDoctors&apos;)
        ///DROP PROCEDURE AddOrUpdateDoctors
        ///GO
        ///CREATE PROCEDURE AddOrUpdateDoctors
        ///    @name nvarchar(50),
        ///	@surname nvarchar(300),
        ///	@specializationId int,
        ///    @id int = 0
        ///AS
        ///IF @id = 0
        ///	BEGIN
        ///		INSERT INTO Doctors([Name], [Surname], [SpecializationId])
        ///		VALUES(@name, @surname, @specializationId)
        ///
        ///		SET @id = scope_identity()
        ///		RETURN @id
        ///	END
        ///ELSE
        ///	BEGIN
        ///		UPDATE Doctors
        ///		SET
        ///		[Name] = @name,
        ///		[Surname] = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20_AddOrUpdateDoctors {
            get {
                return ResourceManager.GetString("20_AddOrUpdateDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;AddOrUpdateAppointments&apos;)
        ///DROP PROCEDURE AddOrUpdateAppointments
        ///GO
        ///CREATE PROCEDURE AddOrUpdateAppointments
        ///    @doctorId int,
        ///	@officeId int,
        ///	@startDate datetime,
        ///	@endDate datetime,
        ///	@patientName nvarchar(50),
        ///	@id int = 0
        ///AS
        ///IF @id = 0
        ///	BEGIN
        ///		INSERT INTO Appointments([DoctorId], [OfficeId], [StartDate], [EndDate], [PatientName])
        ///		VALUES(@doctorId, @officeId, @startDate, @endDate, @patientName)
        ///
        ///		SET @id = scope_identi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _21_AddOrUpdateAppointments {
            get {
                return ResourceManager.GetString("21_AddOrUpdateAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;DeleteOffices&apos;)
        ///DROP PROCEDURE DeleteOffices
        ///GO
        ///CREATE PROCEDURE DeleteOffices
        ///    @id int
        ///AS
        ///DELETE Offices
        ///WHERE Id = @id
        ///
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE [type] = &apos;TR&apos; AND [name] = &apos;Offices_DELETE&apos;)
        ///DROP TRIGGER Offices_DELETE;
        ///
        ///GO
        ///
        ///CREATE TRIGGER Offices_DELETE ON Offices
        ///AFTER DELETE AS
        ///INSERT INTO OfficesChangeLog (OfficeId, Number, Operation)
        ///SELECT Id, Number, &apos;DELETE&apos;
        ///FROM DELETED.
        /// </summary>
        internal static string _22_DeleteOffices {
            get {
                return ResourceManager.GetString("22_DeleteOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;DeleteSpecializations&apos;)
        ///DROP PROCEDURE DeleteSpecializations
        ///GO
        ///CREATE PROCEDURE DeleteSpecializations
        ///    @id int
        ///AS
        ///DELETE Specializations
        ///WHERE Id = @id
        ///
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE [type] = &apos;TR&apos; AND [name] = &apos;Specializations_DELETE&apos;)
        ///DROP TRIGGER Specializations_DELETE;
        ///
        ///GO
        ///
        ///CREATE TRIGGER Specializations_DELETE ON Specializations
        ///AFTER DELETE AS
        ///INSERT INTO SpecializationsChangeLog (SpecializationId,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _23_DeleteSpecializations {
            get {
                return ResourceManager.GetString("23_DeleteSpecializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;DeleteDoctors&apos;)
        ///DROP PROCEDURE DeleteDoctors
        ///GO
        ///CREATE PROCEDURE DeleteDoctors
        ///    @id int
        ///AS
        ///DELETE Doctors
        ///WHERE Id = @id
        ///
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE [type] = &apos;TR&apos; AND [name] = &apos;Doctors_DELETE&apos;)
        ///DROP TRIGGER Doctors_DELETE;
        ///
        ///GO
        ///
        ///CREATE TRIGGER Doctors_DELETE ON Doctors
        ///AFTER DELETE AS
        ///INSERT INTO DoctorsChangeLog (DoctorId, [Name], [Surname], [SpecializationId], Operation)
        ///SELECT Id, [Name], [Surname], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _24_DeleteDoctors {
            get {
                return ResourceManager.GetString("24_DeleteDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;DeleteAppointments&apos;)
        ///DROP PROCEDURE DeleteAppointments
        ///GO
        ///CREATE PROCEDURE DeleteAppointments
        ///    @id int
        ///AS
        ///DELETE Appointments
        ///WHERE Id = @id
        ///
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE [type] = &apos;TR&apos; AND [name] = &apos;Appointments_DELETE&apos;)
        ///DROP TRIGGER Appointments_DELETE;
        ///
        ///GO
        ///
        ///CREATE TRIGGER Appointments_DELETE ON Appointments
        ///AFTER DELETE AS
        ///INSERT INTO AppointmentsChangeLog (AppointmentId, [DoctorId], [OfficeId], [Start [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _25_DeleteAppointments {
            get {
                return ResourceManager.GetString("25_DeleteAppointments", resourceCulture);
            }
        }
    }
}
